name: 'claims_data_warehouse'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'claims_data_warehouse'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  claims_data_warehouse:
    # Staging models - raw data cleaning and standardization
    staging:
      +materialized: view
      +docs:
        node_color: "#F7931E"

    # Intermediate models - business logic transformations
    intermediate:
      +materialized: view
      +docs:
        node_color: "#F7931E"

    # Data marts - final analytical models
    marts:
      +materialized: table
      +docs:
        node_color: "#27AE60"

      # Core business entities
      core:
        +materialized: table
        +docs:
          node_color: "#2ECC71"

      # Analytics and metrics
      analytics:
        +materialized: table
        +docs:
          node_color: "#3498DB"

# Testing configurations
tests:
  +store_failures: true
  +severity: error

# Seeds configurations
seeds:
  +quote_columns: false

# Snapshots configurations
snapshots:
  +target_schema: snapshots
  +strategy: timestamp
  +updated_at: updated_at

# Variables for environment-specific configurations
vars:
  # Timezone for date calculations
  timezone: 'America/New_York'

  # Data quality thresholds
  max_claim_amount: 1000000
  min_claim_amount: 0

  # Lookback periods for metrics
  metrics_lookback_days: 365